version: "3.8"
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda_saramago
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - agenda_saramago_network

  rabbitmq:
    image: rabbitmq
    container_name: agendasaramago_rabbitmq
    ports:
      - "5672:5672"
      - "15673:15673"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - agenda_saramago_network

  datagen:
    build: ./data_gen
    container_name: agendasaramago_datagen
    restart: on-failure
    links:
      - rabbitmq
      - mysql
    networks:
      - agenda_saramago_network

  reactclient:
    build: ./prototype/agenda_saramago
    container_name: agendasaramago_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    depends_on:
      - web
    restart: unless-stopped
    image: agendasaramago-frontend
    networks:
      - agenda_saramago_network
    
  web:
    build: ./agenda-saramago
    image: agenda_saramago
    container_name: agenda_saramago
    restart: on-failure
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - 5001:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=agenda_saramago
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/agenda_saramago
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      - agenda_saramago_network
    
networks:
  agenda_saramago_network: