version: "3.8"
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ies_agenda_2023
      MYSQL_DATABASE: agenda_saramago
      MYSQL_USER: user1
      MYSQL_PASSWORD: ies_agenda_2023
    networks:
      - agenda_saramago_network

  rabbitmq:
    image: rabbitmq
    container_name: agendasaramago_rabbitmq
    ports:
      - "5672:5672"
      - "15673:15673"
    networks:
      - agenda_saramago_network

networks:
  agenda_saramago_network: