version: "3.8"
services:

  rabbitmq:
    image: rabbitmq
    container_name: agendasaramago_rabbitmq
    ports:
      - "5672:5672"
      - "15673:15673"
    networks:
      - agenda_saramago_network

  datagen:
    build: ./data_gen
    container_name: agendasaramago_datagen
    restart: on-failure
    links:
      - rabbitmq
    networks:
      - agenda_saramago_network


  reactclient:
    build: ./prototype/agenda_saramago
    container_name: agendasaramago_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    depends_on:
      - rabbitmq
    restart: unless-stopped
    image: agendasaramago-frontend
    networks:
      - agenda_saramago_network
networks:
  agenda_saramago_network: