version: "3.8"
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ies_agenda_2023
      MYSQL_DATABASE: agenda_saramago
      MYSQL_USER: user1
      MYSQL_PASSWORD: ies_agenda_2023
    networks:
      - agenda_saramago_network

  rabbitmq:
    image: rabbitmq
    container_name: agendasaramago_rabbitmq
    ports:
      - "5672:5672"
      - "15673:15673"
    networks:
      - agenda_saramago_network

  datagen:
    build: ./data_gen
    container_name: agendasaramago_datagen
    restart: on-failure
    links:
      - rabbitmq
      - mysql
    networks:
      - agenda_saramago_network


  reactclient:
    build: ./prototype/agenda_saramago
    container_name: agendasaramago_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    depends_on:
      - web
    restart: unless-stopped
    image: agendasaramago-frontend
    networks:
      - agenda_saramago_network
    
  web:
    build: ./agenda-saramago
    image: agenda_saramago
    container_name: agenda_saramago
    restart: on-failure
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - 5001:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=agenda_saramago
      - SPRING_DATA_MYSQL_AUTHENTICATION_DATABASE=agenda_saramago
      - SPRING_DATA_MYSQL_AUTO_INDEX_CREATION=true
      - SPRING_DATA_MYSQL_HOST=mysql
      - SPRING_DATA_MYSQL_PORT=3306
      - SPRING_DATA_MYSQL_USERNAME=user1
      - SPRING_DATA_MYSQL_PASSWORD=user1
      - SPRING_DATA_MYSQL_DATABASE=agenda_saramago
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - agenda_saramago_network
    
networks:
  agenda_saramago_network: